Feature
tGodson/Rails-Form pull request #1
Opened 2020-07-30 17:16 UTC by tGodson

This Project is about building some forms for Rails

2020-07-30 19:22 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for the effort put into this project.
To move forward, you should fix some issues.

1 :point_right: Kindly set up the github actions

2 :point_right: I got this error when access `http://localhost:3000`
![Screenshot at 2020-07-30 20:02:13](https://user-images.githubusercontent.com/8848104/88963356-a0585d00-d29f-11ea-9cb4-391dd421bb95.png)

3 :point_right: It's preferable to use `users_path` instead of `/users`

4 :point_right: Read the comments left below, please.

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-07-30 19:22 UTC, maelfosso commented on config/routes.rb
> +  post "users", to: 'users#update'
Same routes twice?

2020-07-30 19:22 UTC, maelfosso commented on app/views/users/new.html.erb
> +<%= form_tag('/posts') do -%>
There is no requirements concerning **posts**

2020-07-30 19:22 UTC, maelfosso commented on app/views/users/new.html.erb
> +<!-- <form action="/users" method="POST" accept-charset="UTF-8" >
Always use `users_path` instead of `/users`

2020-07-30 19:22 UTC, maelfosso commented on app/controllers/users_controller.rb
> +  	# @user = User.new(user_params)
Remove comments, please

2020-07-31 02:52 UTC, uryelah requested changes
Hi **Iggy Sani & Godson Tendongze Zeingkeang**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with most of the fixes, there are still some left to implement so make sure to read the comments below carefully and to manually test your project features beforehand to check if it all works. Note also that you are asked to keep some commented-out code for this project in specific.

# Required Changes 🏗️ 🐛 💡

- [ ] Your GitHub linter check is not showing up in the PR, make sure it's working before the next review.

- [ ] This project asks you to keep a commented out form made with the Html form tag and another commented out one using form_tag. Make sure to keep those as instructed at Odin Project.

- [ ] Remember to write descriptive commit messages. 

- [ ] [OPTIONAL] Try to make a form partial and reuse it on new and edit.


-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-07-31 02:52 UTC, uryelah commented on config/routes.rb
> +  resources :user, only: [:new, :create, :update]
- [ ] You are missing the edit route.

2020-07-31 02:52 UTC, uryelah commented on app/controllers/users_controller.rb
> +      render 'new'
- [ ] Prefer symbols over strings, use :new instead of 'new'

2020-07-31 02:52 UTC, uryelah commented on app/controllers/users_controller.rb
> +      render 'edit'
- [ ] Prefer symbols over strings, use :edit instead of 'edit'

2020-07-31 02:52 UTC, uryelah commented on app/models/user.rb
> +  validates :email, presence: true
- [ ] [OPTIONAL] Use Regular expressions or Rails built-in methods to check if the string in the email field is indeed formatted as a vallid email addess.

2020-07-31 07:25 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for applying the suggested changes
However, there are still some issues

1 :point_right: I got this error after creating a new user
![Screenshot at 2020-07-31 08:20:46](https://user-images.githubusercontent.com/8848104/89010614-dc72d880-d306-11ea-9995-311ee8a8b6c3.png)


2 :point_right: Read the comments left below

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-07-31 07:25 UTC, maelfosso commented on app/views/users/new.html.erb
> +<html>
It's not needed. You can remove it.

2020-07-31 07:25 UTC, maelfosso commented on app/controllers/users_controller.rb
> +      redirect_to @user
That route doesn't exist

2020-07-31 07:25 UTC, maelfosso commented on config/routes.rb
> +  resources :user, only: [:new, :create, :update, :edit]
Generally, it's better to use `users` instead of `user`

2020-07-31 07:25 UTC, maelfosso commented on config/routes.rb
> +  post "users", to: 'users#create'
If you replace `resources user` by **`resources users`**, you wont need this two routes anymore

2020-07-31 11:58 UTC, maelfosso approved these changes
# Congratulations :clap: 

Thank you for applying the changes.
It's working like a charm now :smile_cat: 

You can merge it :+1: 

Good continuation :handshake: 

Mael FOSSO

2020-07-31 13:30 UTC, merged